# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e53c63339f7f70b9bf8f3978f2eab958fe90d7aa31bfeb88b22323a2b7181e14d62881150dc033204b0d5d9b1f8f94963cda61548fccddec6b8c11cb5d01e8b

test:
  secret_key_base: beb5130ca74365a65e1b8bd4b65709b9be97af178d793ee43d8162aa918915b1164123b467788998aa2e82ebf2874d9a9341a5f158990825ecb50cf768dee72d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
